### ISSUE TITLE
Problem with bootstrap. add !important for content-box

### ISSUE THREAD

**Issue by DarkAiR** [Grsmto/simplebar#107]
For bootstrap, when used box-sizing: border-box, styles for .simplebar-scroll-content, are not working.
Need to add !important after content-box.
Also same problem with [data-simplebar=init] display: flex - if put the scroller into .tab-content, scroller will not work.

**Comment by Grsmto** [comment]
This is actually great. Nowadays people use css-in-js which does inline css. This avoid people to override the css by mistake and break the plugin. 
Using !important could have the same effect. It's probably a good idea to apply it to every core SimpleBar styles!
However, inline styles are probably better because it can still be override by user using !important (we never know).
