### ISSUE TITLE
Bower/Wiredep need "main" in bower.json

### ISSUE THREAD

**Issue by matthewbryancurtis** [Grsmto/simplebar#135]
Hello and thanks for this project!

I work on an app that's still using Bower/Wiredep to inject JS/CSS into projects. Right now I'm getting this error:

> Running "wiredep:app" (wiredep) task
> 
> simplebar was not injected in your file.
> Please go take a look in "<PROJECT_PATH>/bower_components/simplebar" for the file you need, then manually include it in your file.

I did some research and it seems like simplebar needs this in the `.bower.json`:

``` JSON
"main": [
  "dist/simplebar.js",
  "dist/simplebar.css"
],
```

https://github.com/bower/spec/blob/master/json.md#main

I was going to file a PR to add this, but I couldn't figure out how the `.bower.json` was getting generated. If you're still interested in supporting Bower and could give me a tip, I'd be glad to file that PR.

Thanks!

**Comment by Grsmto** [comment]
Hey!
So Simplebar doesn't do anything specific regarding Bower. I didn't even know it was on Bower! It's probably from a very old version.
If you can use npm, I think I would prefer to unregister Simplebar from Bower instead of supporting it, except if it's blocking for anyone.
What blocks you from importing it from npm instead of Bower?

**Comment by matthewbryancurtis** [comment]
Yeah, I've realized Wiredep is unmaintained and Bower is on the ropes. I had been using Wiredep to auto-inject dependencies, but realized it was pulling in unused code - so I'm removing it from my project anyway.

Will use npm, thanks for looking in to it!
