### ISSUE TITLE
IE8 - Always visible scrollbars

### ISSUE THREAD

**Issue by dflynn15** [Grsmto/simplebar#14]
I'm not sure if this is expected or not, but for IE8 on Windows 7 the plugin looks like:
![screenshot 2015-09-15 14 44 36](https://cloud.githubusercontent.com/assets/1205286/9886465/6b8d797e-5bb8-11e5-8db6-8f735240a920.png)

I'm going to look into it, but if you have any ideas are pain places to look that would help a lot :+1:

**Comment by Grsmto** [comment]
Hi,

I'm not sure what's the problem on your screenshot but if it's related to the fact that the bar doesn't disappear and is not rounded this is just because IE8 doesn't support `border-radius` and `opacity` properties.
If you want the scrollbar to disappear you can apply `visibility: hidden` in css. I let you figure out where!

**Comment by dflynn15** [comment]
Nice! I had just started, so I'll go ahead and tack that on for a fallback and submit a PR :+1:

**Comment by dflynn15** [comment]
PR is in #15

**Comment by Grsmto** [comment]
This should be fixed with the latest release!
