### ISSUE TITLE
Native scroll appears when used inside flex column

### ISSUE THREAD

**Issue by SavchukSergey** [Grsmto/simplebar#142]
Native scrolls do not hide when simplebar is used on element with 
```css
  flex-direction: column;
```

See https://codepen.io/sergey_savchuk/pen/YervoO

**Comment by Grsmto** [comment]
Unfortunately we can do anything about this because we would have to handle every possible CSS property that the user could break Simplebar with.
You should not apply any custom style to the div handled by Simplebar. You should use a wrapper, or an extra inner div to style your content and not use the one you apply Simplebar on.
I will close this but I will try to improve the documentation to make this clearer as there are many issues related to this.
