### ISSUE TITLE
[SOLVED] Auto scroll not working with package vue-scrollto

### ISSUE THREAD

**Issue by Sweetyy** [Grsmto/simplebar#193]
Hi,

I'm using the package '**vue-scrollto**' which is working fine with the native scrollbar but when i'm using your package and trying to use just the basic simplebar, the auto scroll is not working anymore when i click on an element.

I tested on Windows 10 with VueJs 2 and Quasar 0.17.5 .

Here is the link with the auto scroll package i'm using : https://www.npmjs.com/package/vue-scrollto

Is there any conflict between the two packages that can break the auto scroll by clicking ?

Thanks in advance for your help,

Sweetyy

**Comment by Grsmto** [comment]
This is because SimpleBar is not using anymore the div you applied it on.
You will probably have to use the `container` option of vue-scrollTo so it receives the right SimpleBar container.
Thing is that `container` option seems to be just taking a query selector so you'll have to hack around a bit with something like so:
for vertical scroll:
`container: "#your-simplebar-element .simplebar-scroll-content"` 
for horizontal scroll:
`container: "#your-simplebar-element .simplebar-content"` 

This is not ideal but that should be able to solve your idea.

**Comment by Sweetyy** [comment]
Wow thank you so much for you quick answer @Grsmto ! I will try it and give you my feedback !

**Comment by Sweetyy** [comment]
It's working perfectly ! Thank you ! Congratulation for you package ! Just awesome :)

**Comment by Grsmto** [comment]
That's awesome! Good luck with your projects.
