### ISSUE TITLE
simplebar scroll to body

### ISSUE THREAD

**Issue by riiccardo** [Grsmto/simplebar#196]
can u provide an example in `codepen` for us ?

i do it by my self `wrap` all element into another `div` instead of `body` add `simplebar` to element

 but scroll dosen't work and simplebars `element` has `hidden visibility`

please make an example of :

1- add simplebar to `body` my mean to that div wrap all the content 

2- and `blockscroll` like `overflow: hidden` when an element `is-active` like when offCanvas is opened

Regards Sadegh 👍

**Comment by Grsmto** [comment]
Hi @riiccardo 
If you want to do this I recommend to use another plugin because SimpleBar doesn't currently support this (it should work fine but I don't recommend it) [as you can see in the README](https://github.com/Grsmto/simplebar#warning-warning).

However blocking the scroll is a feature that I want to support, so I'll reference this issue and open a new one regarding this point.
