### ISSUE TITLE
Problems with scroll events

### ISSUE THREAD

**Issue by exteon** [Grsmto/simplebar#206]
I'm having the following problem with the scroller:
- Using .getScrollElement() to bind to 'scroll' event of the scrolled element
- Resize browser, scroll direction changes. Scrolled element changes.
- No more scroll events for my handler

Combined with the evangelical problem of:
- Concerning scroll events, the plugin does not provide a drop-in replacement for the element, one needs to change any handlers binding to accommodate your scroller

Leads me to one reasonable solution/request: 
Instead of transpiring .getScrollElement(), why not proxy events to the container element? (listen on scroll container, dispatch on container). The scroll event doesn't bubble, so with this effort it will not only not break scroll listeners, but provide drop-in compatibility for the container.

Update for anyone running into the same problem: I've gotten around this by binding to both .simplebar-content, .simplebar-scroll-content elements inside container.

**Comment by Grsmto** [comment]
Hey,
Thanks for the report, I think your idea is really good. I actually thought about a potential solution like this with proxying but I didn't get it to work. As you can't simply "forward" an event to another element, you have to recreate a new event as far as I know. I'll take a look again.

> Resize browser, scroll direction changes. Scrolled element changes.
This specific issue should be fixed in the next version of SimpleBar as I'm radically changing the way the plugin works and there should be only one single div that handles both scroll direction instead of 1 for each axis at the moment.

**Comment by Grsmto** [comment]
So update on this, I confirm this is impossible in JS to "proxy" events. The only one proxy-able is `click`.
So unfortunately you won't ever be able to simply listen to your original `scroll` element event and expect it to work :/

**Comment by Grsmto** [comment]
I close this since latest version fixes the actual bug in there.
