### ISSUE TITLE
Possible to add margin-bottom to bring scroll off the edge?

### ISSUE THREAD

**Issue by tophat1986** [Grsmto/simplebar#256]
Is it possible to add a "margin-bottom" to the scroll bar to lift it up from touching the bottom of the div?

I know I can add the margin to the container of the content, but this design is unwanted because I'd like the fade effect to show their's content slipping underneath the div at the bottom with the icons.  I don't want the margin space to show on the div, but on the scroll bar ideally?

![image](https://user-images.githubusercontent.com/29504604/51115428-2fa63880-1800-11e9-95d3-8b44d653e6a7.png)

**Comment by adjourn** [comment]
Yes it is ([demo](https://jsfiddle.net/drbuw90q/)):

```css
.simplebar-track.simplebar-vertical {
  margin-bottom: 25px;
}
```
1. Add custom class too, otherwise all `simplebar` vertical scrollbars are affected, e.g .`custom .simplebar-track.simplebar-vertical`
2. Scrollbar doesn't (seem to) resize, so it's not 100% accurate ratio but the difference shouldn't be noticeable if you keep margin relatively small
3. I didn't test it in different situations, I cannot guarantee that it doesn't mess something else up, you have to test it yourself

**Comment by Grsmto** [comment]
The scrollbar size is relative to the content height so I would say this is correct.
You can also use `bottom: 25px` instead of margin, as by default SimpleBar is set to `bottom: 0`.
