### ISSUE TITLE
Let the scrollbar to remain hidden on container "mouse enter" event

### ISSUE THREAD

**Issue by alexhx5** [Grsmto/simplebar#260]
## Current Behavior

Right now the scrollbar is constantly appearing/disappearing when you:

- move the cursor over different elements inside the container with the simplebar
- move the cursor inside the container with the simplebar

## Expected behavior

To have a prop that would disable this behavior:

`data-simplebar-show-on-container-enter="false"`

**Result - scrollbar has only 2 of 3 triggers turned on:** 
- show scrollbar on simplebar container enter = `false`
- show scrollbar on scroll start = `true`
- show scrollbar on scrollbar hover = `true`

**Comment by Grsmto** [comment]
Thanks for your request,

I would rather just have classes for this instead of adding options.
Right now SimpleBar doesn't have any but the main container could have a `.scrolling` class and then users could do whatever they want with CSS.

>* show scrollbar on simplebar container enter = `false`
I suppose for this one you could just override the default CSS to get the scrollbar hidden

>* show scrollbar on scroll start = `true`
Doable with a new `.scrolling` class on the container 

>* show scrollbar on scrollbar hover = `true`
We already have a class for that on the scrollbar element itself (it should probably be on the container instead...).

So I think the only thing to do to have this fully supported is adding that new class on scroll. Should be really straightforward to add.

**Comment by scarcoco** [comment]
so this not done ?
