### ISSUE TITLE
scrollbar is not visible until users scrolls 

### ISSUE THREAD

**Issue by forethoughtde** [Grsmto/simplebar#262]
## Current Behavior

I use the vue.js plugin for enabling scrollbar visible all the time. For some reasons, the scrollbar is not visible until user scrolls for the first time then it stays visible. 

I use the custom attribute `data-simplebar-auto-hide="false"` to make the scrollbar visible at all times. 

```
<simplebar class="siemens-cross-section-tool-sidebar" data-simplebar-auto-hide="false">
        <div id="componentListContainer">
            <div class="scst_component" v-for="(vCoordinate, index) in turbines"
                 :key="index"
                 v-on:mouseover="mouseOver($event, vCoordinate['id'])"
                 v-on:mouseleave="mouseLeave($event, vCoordinate['id'])" :id="vCoordinate['id']">
                <img src="../../assets/icon_check_2x.png" alt="">
                <p>{{ vCoordinate['name'] }}</p>
                <div class="scst_dots_wrapper">
                    <div v-for="c in colors"
                         class="scst_color_dot"
                         v-bind:style="{ 'border-color': vCoordinate['colors'][c['name']]['hex'], 'background-color':  vCoordinate['colors'][c['name']]['status']}"
                         v-on:click="selectColor(c['name'], vCoordinate['id'])">
                    </div>
                </div>
            </div>
            <p v-if="isShow()" class="scst_no_result">
                No results!
            </p>
        </div>
    </simplebar>
```

```
import simplebar from 'simplebar-vue';
import 'simplebar/dist/simplebar.min.css';

export default {
        components : { simplebar }
}
```

## Expected behavior

Scrollbar should be visible from the start. 

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 3.1.3
| Browser          | Electron app (Chrome)
| npm/Yarn         | 1.5.1
| Operating System | MacOS

**Comment by Grsmto** [comment]
Weird. In the React env it works fine: http://grsmto.github.io/simplebar/examples

I don't see why Vue would make any difference. You're sure you don't have any CSS clashing?

**Comment by adjourn** [comment]
I've never worked with Vue so I can't say by just looking at your code but I have an idea:
 
If you render simplebar DOM yourself and let `simplebar` to hook into it (attach listeners etc), [it doesn't modify classes](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/src/simplebar.js#L257-L348) and DOM ends up with what ever classes you added (or didn't add).

**Fix:** if you create DOM yourself and `autoHide: false`, make sure that scrollbar has `simplebar-visible` class (or what ever you use if using custom class names), otherwise it won't show up at first.


@Grsmto I don't use it myself but I believe that [`simplebar-react`](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar-react/index.js) has same "bug".

**Comment by adjourn** [comment]
I've never worked with Vue so I can't say by just looking at your code but I have an idea:
 
If you render simplebar DOM yourself and let `simplebar` to hook into it (attach listeners etc), [it doesn't modify classes](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/src/simplebar.js#L257-L348) and DOM ends up with what ever classes you added (or didn't add).

**Fix:** if you create DOM yourself and `autoHide: false`, add `simplebar-visible` class (or what ever you have if using custom class names) to scrollbar yourself, otherwise it won't show up until you scroll.


@Grsmto I don't use it myself but I believe that [`simplebar-react`](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar-react/index.js) has same "bug".

**Comment by adjourn** [comment]
I have an idea.

If you render `simplebar` DOM beforehand (which I think `simplebar-vue` does, never used it) and let `simplebar` to hook into it (attach listeners etc), [it doesn't modify classes](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar/src/simplebar.js#L257-L348) and DOM ends up with what ever classes are added (or didn't add).

**Fix:** if DOM is created beforehand and `autoHide: false`, add `simplebar-visible` class (or custom class if using those) to scrollbar on render, otherwise it won't show up until it's scrolled.


@Grsmto I use my own React component but I believe that [`simplebar-react`](https://github.com/Grsmto/simplebar/blob/master/packages/simplebar-react/index.js) has same "bug".

**Comment by xavimajoral** [comment]
Yup, it happens the same with me with simplebar-react

**Comment by mst5295** [comment]
I use the Vue plugin of Simplebar. Here is an example of how I use the simplebar and which CSS styles I use:

list.vue
```javascript
<simplebar class="simplebar-container"
 data-simplebar-auto-hide="false">
      <v-list>
        ...
      </v-list>
</simplebar>
```  

list.styl  
```
.simplebar-container {
    margin-top: 16px;
    // 100% container height - search - margin - footer
    max-height: calc(100% - 56px - 16px - 56px);
  }
```
The following GIF shows a section of my Chrome DevTools Elements panel.
After loading the `div class` contains `simplebar-scrollbar`.   
As soon as I scroll, it changes to `simplebar-scrollbar simplebar-visible`.  

![html-style](https://user-images.githubusercontent.com/23235129/54922048-9f732680-4f07-11e9-89fc-1ec58f7d4e97.gif)

 `data-simplebar-auto-hide`is probably not checked when loading the component. As a result, `scrollbar-visible` is not set.  
  
@Grsmto, do not know to what extent you have dealt with this problem, but perhaps my comment will help you to solve it
