### ISSUE TITLE
Use passive touch and wheel listeners

### ISSUE THREAD

**Issue by olafcm** [Grsmto/simplebar#270]
Simplebar does not use [passive listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md). It is [recommended](https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners) to set the passive option on touch and wheel event listeners can improve scrolling performance.

It seems this call `_this3.el.addEventListener(e, _this3.onPointerEvent, true);` on line 3952 of Simplebar can be switched to passive ("This frees the browser up to respond to scrolling immediately without waiting for JavaScript, thus ensuring a reliably smooth scrolling experience for the user.").

**Comment by adjourn** [comment]
> It seems this call `_this3.el.addEventListener(e, _this3.onPointerEvent, true);` on line 3952 of Simplebar can be switched to passive ("This frees the browser up to respond to scrolling immediately without waiting for JavaScript, thus ensuring a reliably smooth scrolling experience for the user.").

This assumption is incorrect because `onPointerEvent` sometimes calls `preventDefault`. Passive event listener signals browser that callback never prevents default, browser can then safely respond to event right away and not wait until callback is done.

Simplebar could probably utilize `passive` somewhere but then we'd have to organize events better and most likely split them in different ways, i.e use different callback functions, some passive.

`addEventListener('scroll', this.onScroll);` doesn't need to be set passive, since `scroll` event cannot be canceled and it should behave as it's passive anyway.

**Comment by Grsmto** [comment]
From what I see we don't have any event handler that could use `passive` at the moment. 
Feel free to re-open if you identify one more precisely!

**Comment by pocka** [comment]
@Grsmto 

> From what I see we don't have any event handler that could use passive at the moment.

After a quick investigation, I found the lines.

When using simplebar, Chrome outputs these logs with verbose level:

![Screenshot from 2019-07-13 12-30-29](https://user-images.githubusercontent.com/13316015/61166541-2b1dcb00-a56a-11e9-95bc-8c5e901d8bab.png)

where `c-2.js:4044` is

![Screenshot from 2019-07-13 12-31-28](https://user-images.githubusercontent.com/13316015/61166548-64563b00-a56a-11e9-89cb-ecb2cf240fe6.png)

which comes from [packages/simplebar/src/simplebar.js#L384](https://github.com/Grsmto/simplebar/blob/simplebar%404.1.0/packages/simplebar/src/simplebar.js#L384).

**Comment by KevPat** [comment]
I have this problem as well. Only thing holding me back.

![image](https://user-images.githubusercontent.com/7307508/63234298-424f7880-c1fa-11e9-83b1-0198b79227c4.png)
