### ISSUE TITLE
Horizontal Scrolling Container & flex

### ISSUE THREAD

**Issue by elalemanyo** [Grsmto/simplebar#284]
Hi,
It is not possible to scroll to the end of the container. `simplebar-offsetcontainer` have inline right value making not possible to see the las part of the container. Is maybe because of using flex?
https://codepen.io/elalemanyo/full/vPZRZb

Thanks!

**Comment by Grsmto** [comment]
It seems to work fine for me, can't reproduce the bug you have.
However the container is small and chop the images. I think this bug is because the content is images and the images are not loaded yet when simplebar does its calculation.
The only solution I see for this is to either apply a fixed size to your images (width and height) or to apply simplebar only *after* the images are loaded.

**Comment by Grsmto** [comment]
Try with the latest version. Now that we have a resize observer, it should recalculate automatically when your images are loaded. That should hopefully solve your issue.

**Comment by elalemanyo** [comment]
@Grsmto still not working for me. You can check it here: https://codepen.io/elalemanyo/pen/vPZRZb
