### ISSUE TITLE
To polyfill or not to polyfill?

### ISSUE THREAD

**Issue by Grsmto** [Grsmto/simplebar#314]
Currently SimpleBar use `babel-preset-env` with a Browserlists setup. During transpilation, some polyfill are added via `core-js`.
The problem is that the user might not need these polyfills if they target only modern browser.

Our Browserlists setup is the default recommended one so the polyfills are not that big but I'm not sure what's the industry standard regarding this. I know that it's recommended to transpile but it can be done in so many different ways that I'm not sure anymore.

- Should we keep transpiling with polyfills?
- Is there a way to provide 2 bundles, 1 with polyfills and 1 "raw"? I don't think that's possible.

cc @andersk @adjourn

**Comment by andersk** [comment]
As far as I can tell, the JS community hasn’t yet standardized on a specification for distribution of pre-transpiled code. We only have `pkg.main` for CJS/UMD modules of ES5 code and `pkg.module` for ES6 modules of otherwise-ES5 code. There’s a [`pkg.ecma` proposal](https://github.com/dantman/package-ecma-version-field-spec#packagejson-ecma-version-field-spec) that doesn’t seem to have had any adoption by bundlers yet.

One thing we could do easily is include `src/` in the package so that users who know what they’re doing can `import SimpleBar from "simplebar/src/simplebar.js"` directly. We probably ought to be including `src/` anyway because `dist/simplebar.esm.js.map` refers to it.

**Comment by Grsmto** [comment]
Yeah afaik the current setup was the most optimised possible but I was still wondering if there was any way to improve that.

However even by doing `import SimpleBar from "simplebar/src/simplebar.js"` with a bundler like Webpack and usual setup `node_modules` are not being transpiled, so user would have to configure his bundler etc. So no much benefit.

One thing tho, the bundle could probably be reduced a bit because right now some features are transpiled down to ES5. I think we could transpile down only to anything ES-stable (so prob ES6-7?) and let the user's bundler do the job if they want to polyfill lower than the default.

Of course that's only for consumers of the module version (so in theory modern setups that likely use Babel or equivalent anyway). The UMD would stay untouched.

Thanks for your input!

**Comment by andersk** [comment]
Because (like you said) `node_modules` are not usually transpiled, `dist/simplebar.esm.js` should also stay the way it is. It would be unexpected for `import SimpleBar from "simplebar"` to pull in anything other than ES5 code.

Adding `src/` to the package would give users a way to explicitly opt into pulling in the ES6+ code and accepting responsibility for configuring their bundler to handle it as desired.
