### ISSUE TITLE
Doesn't work with <textarea>

### ISSUE THREAD

**Issue by borkafight** [Grsmto/simplebar#333]
Hey!

It's very cool plugin but, unfortunately, it seems doesn't work with <textarea>.
Or am I doing something wrong?

Thanks!

**Comment by Grsmto** [comment]
Hi,
Yes unfortunately that's a known limitation, it's explained in [the caveat section of the README](https://github.com/Grsmto/simplebar#5-caveats). If you need such thing, I would suggest https://kingsora.github.io/OverlayScrollbars/
The reason is that it would need too much effort and lines of code to support this and that would make the library heavier and kind of lower the purpose of it.

**Comment by punkpeye** [comment]
It doesn't seem like the latest version of OverlayScrollbars support textarea either

https://github.com/KingSora/OverlayScrollbars/discussions/504
