### ISSUE TITLE
Ability to jump to scroll position in track

### ISSUE THREAD

**Issue by mcosier** [Grsmto/simplebar#34]
For anyone else who is interested:

```
 SimpleBar.prototype.trackJump = function(e) {
        var pos = this.$track.offset()[this.offsetAttr];
        var eventOffset = e.pageY;
        if (this.scrollDirection === 'horiz') {
            eventOffset = e.pageX;
        }
        var dragPos = (eventOffset - pos) - (this.$scrollbar.height() / 2);
        var dragPerc = dragPos / this.$track[this.sizeAttr]();
        var scrollPos = dragPerc * this.$contentEl[0][this.scrollSizeAttr];
        this.$scrollContentEl[this.scrollOffsetAttr](scrollPos);
    };

SimpleBar.prototype.init = function () {
<cut>
this.$scrollbar.on('click', function (e) {
            e.preventDefault();
            e.stopPropagation();
            return false;
        });
this.$track.on('click', $.proxy(this.trackJump, this));
}
```

**Comment by Grsmto** [comment]
Hi @mcosier thanks for this!
As this feature is not supported by the native "floating" scrollbar (on mac OSX for example) I don't think this will ever be implemented in Simplebar (as I'm trying to keep it light and simple).
But don't hesitate to fork the project to implement this feature and link it in this issue in reference for users that would need it too! (actually pasting your solution here already did the job :) )
Otherwise if you need more advanced features you should take a look at the plugins I linked on the readme file.
