### ISSUE TITLE
MutationObserver rewrite Angular's one - performance issue

### ISSUE THREAD

**Issue by tamtakoe** [Grsmto/simplebar#343]
**Describe the bug**
SimpleBar uses MutationObserver which works bad in Angular 2+ applications. It can slow page down or hang it. Especially in Firefox because it has no ResizeObserver and uses MutationObserver fallback

**Reproducible example**
https://stackblitz.com/edit/angular-mutationobserver-bug?file=src%2Fapp%2Fapp.component.html

**How to fix**
Check and use Angular MutationObserver according this issue https://github.com/angular/angular/issues/26948

or

Don't use MutationObserver if browser has no ResizeObserver

**Environment**
Last version of SimpleBar, Angular 2+, Any last versions of browsers

**Comment by Grsmto** [comment]
I'm not sure to understand this issue you linked but if that's really the case and you can't use a MutationObserver in a 3rd party code with Angular, that's pretty crazy to me. 
I'm not sure what would be a good solution for this because it seems to be more of an Angular issue than SimpleBar.
Maybe calling the `SimpleBar.removeObserver()` would fix it? But really not sure.

**Comment by hc-codersatlas** [comment]
The linked issues says you can use MutationObserver in a 3rd party code, but just in presence of Angular's to use theirs instead of instantiating a brand new 1.

**Comment by Grsmto** [comment]
Closing this since we don't ship MutationObserver anymore.
