### ISSUE TITLE
Using Device Mode in Chrome DevTools's cause the simplebar-content-wrapper class to have a padding-right of 20px

### ISSUE THREAD

**Issue by exilvm** [Grsmto/simplebar#366]
**To Reproduce**
1. Open this demo: http://grsmto.github.io/simplebar/
2. Open the Chrome DevTools and see how the simplebar-content-wrapper class doesn't have a right padding
3. Activate the Device Mode in the DevTools menu
4. Observe how the simplebar-content-wrapper class gets a right padding of 20px, even after you deactivate the Device Mode and close the DevTools, the padding will remain.

**Additional context**
This bug makes debugging my web app using the DevTools harder.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | v4.1.0
| Browser          | Google Chrome v76.0.3809.132
| npm/Yarn         | NPM v6.9.0
| Operating System | Windows 8.1

**Comment by Grsmto** [comment]
I suppose this is because the plugin has trouble going from a floating scrollbar ("device mode" of the Chrome dev tool) to a normal non-floating scrollbar.
However this scenario shouldn't really happen in real life for normal user (other than developers like you're experiencing), so I would define this as a relatively minor issue.
