### ISSUE TITLE
Forced Reflow in constructor

### ISSUE THREAD

**Issue by abettadapur** [Grsmto/simplebar#371]
**Describe the bug**
This is similar to #162, but I am on v4.0.0

Calling the constructor SimpleBar() causes a forced layout, which can take up to 80ms on my site.

![image](https://user-images.githubusercontent.com/2415669/65470926-070c1f00-de22-11e9-9de6-b872b5e03f4a.png)

**To Reproduce**
Call the SimpleBar() constructor while capturing a Chrome trace.

**Expected behavior**
No reflow should occur.

**Additional context**
I see #162  was closed, but I still see reports of this issue with no further resolution

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 4.0.0
| Browser          | Chrome latest
| Operating System | Windows/Mac

**Comment by Grsmto** [comment]
Hi,
Yes there are definitely still opportunity for performances improvements. I think this depends as well a lot of the element on which you apply SimpleBar, the complexity of your DOM etc.
Could you give more details on your usage?

Could you start by updating to the latest SimpleBar version? That shouldn't impact your test but you're on a quite old version now.

**Comment by abettadapur** [comment]
Thanks for replying!
I will update to the latest version and let you know if anything changed.

One place I noticed it happening every time was with the call to `getScrollbarWidth`. This value doesn't change and could be cached. I can file a PR for this

**Comment by Grsmto** [comment]
There might be one other thing that makes the `scrollbarWidth()` slow is that we reworked it recently in #325 and it's now using `getBoundingClientRect` instead of `offsetWidth` which is much slower I think (didn't do any benchmark but from the top of my head).

Actually the `scrollbarWidth()` is already cached and the cache is flushed only on `window.resize` so it should impact only on init.

Only if you have multiple instance of SimpleBar on your page, you can multiply this issue because there is no caching across instances. There was a plan to work on that in #205 as well.

I see 2 opportunities to improve performances in this function:
- cache the value across instances (that would probably require a global variable?) see #205
- find another way to solve #325 by rolling back usage of `offsetWidth` which is faster but then find another workaround

**Comment by abettadapur** [comment]
I meant the approach for #205, where this value should never change throughout the life of the application. Would require a module level variable, yes

**Comment by abettadapur** [comment]
I will submit a PR for #205

**Comment by abettadapur** [comment]
@Grsmto I also authored #374, which delays the expensive portion of the initialization to a later tick, which improves the first paint experience for complex layouts. Let me know what you think

**Comment by abettadapur** [comment]
After learning more about this library and thrashing, it is pretty clear **why** the thrashing is occurring. Unfortunately, its less clear how to fix it :)

The main issue is that `recalculate` writes and reads DOM properties in an interleaved fashion. This is likely because these operations are all dependent on each other

![image](https://user-images.githubusercontent.com/2415669/65561043-e4e3d100-def5-11e9-9755-d0cf6d3ac93e.png)
For example here, we modify the margin/padding of some elements, and then immediately request the boundingRect. This unfortunately causes the thrashing issue. On small sites (like the demo site) its not noticeable, but becomes a problem on complicated layouts

**Comment by Grsmto** [comment]
You're right it's something I wanted to work on for a long time but it always stayed on the backlog's bottom list :)
We could use/do something like fastDOM for this. I'm actually working on this right now. Added some other hints in #372

**Comment by Grsmto** [comment]
I'm closing this since the library codebase has changed a lot since then. We rely a lot less on `getBoundingClientRect()`, so if anyone notice perf problems please open a new issue!
