### ISSUE TITLE
Errors in a height changing div

### ISSUE THREAD

**Issue by vince1995** [Grsmto/simplebar#414]
**Describe the bug**

Hi, I've got a list with some entries in my document which are accordion items. If I close an accordion with a smooth animation and the simplebar disappears it throws an error event. This error is only visible to me when the following code is provided:

`window.addEventListener("error", e=>...);`

**To Reproduce**
I can't reproduce in CodeSandbox. :(

But here's a gif: 

![simplebar](https://user-images.githubusercontent.com/15120985/69240349-8d33b000-0b9c-11ea-91e6-b85309f6bea6.gif)

**Expected behavior**
There should be no error fired.

**Additional context**

The list itself is a flex-box and is also wrapped in a flex-box.

The browsers are throwing different error. Chrome throws `ResizeObserver loop limit exceeded`, FF `ResizeObserver loop completed with undelivered notifications.`, Edge and Safari don't throw anything.

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 5.0.7
| React-SimpleBar        | 2.0.10

**Comment by Grsmto** [comment]
Hi,

Is that affecting your application specifically? In theory this error message can be ignored, I don't why it triggers an `error` event. You can check this [SO question about it](https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded).

The callback of the `resizeObserver` is debounced so it shouldn't actually loop.

**Comment by vince1995** [comment]
It's affecting because I have to implement a check if the error is coming from ResizeObserver to prevent the default error handling.

**Comment by weldonla** [comment]
The problem comes from recalculate firing too often when it animates. If you increase the throttle shown in the picture below, it will prevent that error from getting called. 

![image](https://user-images.githubusercontent.com/9355344/123684758-dd183580-d81b-11eb-9c38-af3dad806a32.png)

@Grsmto I was under the impression from another post somewhere that you might not be putting out a version where you could adjust the throttles. I forget where I read it though. But so I made a version that allows access to change the throttle for recalculate. I hope that's ok. I didn't really change the readme or documentation. I was kinda lazy about it. If there is something wrong with the way I did this or if you would prefer me doing it as a pr or something, please let me know. I'm kinda inexperienced and don't know the proper procedure for these kind of things. Thanks for such a great plugin btw! We're using aurelia and it's the only custom scrollbar I could get to work with our project.

If anyone is interested here are the links to the version with the change.

https://www.npmjs.com/package/simplebar_weldonla

https://github.com/weldonla/simplebar

**Comment by Grsmto** [comment]
Closed #611
