### ISSUE TITLE
Can't assign an object to data-simplebar-class-names

### ISSUE THREAD

**Issue by danfinch100** [Grsmto/simplebar#457]
I have this situation with a styled React component:

![image](https://user-images.githubusercontent.com/18436964/76676978-c3b88f00-65c0-11ea-861b-2938fdc5f8de.png)

...as you can see the json object that should me merged with the simplebar classNames object is the string representation of an object at the point when it needs to merge. 

I can work around this as follows:

![image](https://user-images.githubusercontent.com/18436964/76677051-65d87700-65c1-11ea-9a82-6f27a05a7b10.png)

but this doesn't seem ideal.

Thanks

**Comment by Grsmto** [comment]
Hi,

This API should be deprecated since it's not doing what it looks like it does. This is to change the SimpleBar internal classes but if you do so, it will break the plugin if you don't as well update the internal CSS accordingly.

Your "workaround" is really much how you should do to style SimpleBar. It's not ideal but that's exactly how I used to style most of 3rd party plugins in CSS-in-JS environment anyway from my experience.

I'm leaving this open since again, I think we should deprecate this API.

**Comment by stevebauman** [comment]
Can we simply allow a JSON string and then `JSON.parse()` it in the `getOptions()` helper method?

```vue
<Simplebar data-simplebar-class-names="{ 'vertical': 'simplebar-vertical custom-classname' }">
    <slot />
</Simplebar>
```
