### ISSUE TITLE
Lazy load implementation 

### ISSUE THREAD

**Issue by yannicke** [Grsmto/simplebar#458]
I would like to implement a lazy loading for my images in my simplebar content with angular.

I didn't find anything about that in the documentation and I have no idea how to do that. 

I would like my images to load only when in the viewport, has anyone ever done this?

Thank you :)

**Comment by Grsmto** [comment]
Hi!

You should use the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). This should be straight forward to implement, basically you should set the `src` value of your image only when the viewport gets close to the image.

However I think this is pretty much unrelated to SimpleBar since it should work exactly the same with or without SimpleBar. That's why there is no documentation for it.

I'm closing this for now then! good luck

Hope that helps!
