### ISSUE TITLE
Method to scroll

### ISSUE THREAD

**Issue by ferdydurque** [Grsmto/simplebar#460]
Is there a method to reset/scroll to the initial position or at certain position? 
I try $(el).scrollTop(0) ... but no result.

Thanks

**Comment by shavidzet** [comment]
Please see: https://github.com/Grsmto/simplebar/issues/402#issuecomment-549023910
So code looks like:
```js
scrollEl.querySelector('.simplebar-content-wrapper').scrollTop = '200'
```

It works, but it will be better to have built-in support to achieve same functionality instead of selecting nested dom...

**Comment by Grsmto** [comment]
Hi guys,

It's documented [here](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#trigger-programmatical-scrolling).

It seems like people have troubles to find the documentation (since there is a lot of issues for the same problem), I'm happy to take suggestions to improve visibility of the documentation if you have any!
