### ISSUE TITLE
Doesn't work with requirejs.

### ISSUE THREAD

**Issue by kirimaks** [Grsmto/simplebar#467]
I cannot make it work work with requirejs.
I added simplebar to requirejs config and looks like it's loaded fine. After that I have some div with table inside which is builded in js code. When building is finished I'm calling:

`new SimpleBar(document.getElementById('#div-with-table'));`

After that div with table just become blank.
I don't have any custom styles on div or table. Seems simple bar is loaded normally because I tried to call recalculate() and other methods, and I don't see any errors. Tried in safari, Chrome and FF.

**Comment by Grsmto** [comment]
So it doesn't seem to have anything to do with require.js if you don't have any error.
Just keep in mind that this won't work for a `table` element, it's a [known limitation](https://github.com/Grsmto/simplebar/tree/master/packages/simplebar#5-caveats).

I will close this until you get to provide an example because otherwise this doesn't really give me any hint to fix it!
Feel free to comment with a link to an example so I can investigate further and re-open the issue.
