### ISSUE TITLE
Content height jumping during SSR with React

### ISSUE THREAD

**Issue by Andriiuxa** [Grsmto/simplebar#481]
If you wrap something in <SimpleBar> during SSR it will be rendered with height: 0 and only on client side it will calculate the height of the content that is inside and render it properly which results in a lot of jumping content during renders. By reading the source code it seems like it is intended: 
```javascript  
init() {
    // Save a reference to the instance, so we know this DOM node has already been instancied
    SimpleBar.instances.set(this.el, this);
    // We stop here on server-side
    if (canUseDOM) {
      this.initDOM();
      this.scrollbarWidth = this.getScrollbarWidth();
      this.recalculate();
      this.initListeners();
    }
  }
```
But I find it very wierd that nobody is bothered by it, so I thought I am missing something? So I guess my only questions are: Is it intended and it is just the limitation of the library or am doing something wrong and I am the only dumbass with this issue?

**Comment by Grsmto** [comment]
Hi,
To avoid this to happen you need to make sure the element you're applying SimpleBar to is behaving well **before** applying SimpleBar to it. There is no "one solution fits them all" for this since it depends of your layout/css but what you need to do is have your parent element have a defined `height`.

Keep in mind that it's not only for SSR but if Javascript is disabled, your layout would be broken as well
