### ISSUE TITLE
Migration from the 'simplebar' to the 'simplebar-core'

### ISSUE THREAD

**Issue by yshukh** [Grsmto/simplebar#596]
Hello,

Could you please clarify some moments and help to understand one more nuance?

I've just migrated from the _'simplebar'_ to the _'simplebar-core'_ dependency in the Angular project. I was frustrated when it had turned out that `data-simplebar` directive isn't supported there.  Also, I saw _'simplebar-angular'_ edition here, but I didn't manage to figure out if is it possible to add the scrollbar at least with `new SimpleBar(...)` syntax not mention already old, nice `data-simplebar` way.

So some moments:
1. Is it worth to expect directive way of initialization in the _'simplebar-core'_ edition? (yeah, I have the superficial understanding that _'simplebar-core'_ has got rid of heavy libs that were most likely helpful for exactly `data-simplebar` directive support, but anyway)
2. Does _'simplebar-angular'_ edition support at least the `new SimpleBar(...)` syntax?

Nuance: 
1. Is it true that whole edition _'simplebar'_ uses `.queryAll("[data-simplebar])` to support the directive way of initialization and that this way may cause performance issues?

Thanks a lot 🤍 🤎 💔

**Comment by Grsmto** [comment]
Hi!

> Is it worth to expect directive way of initialization in the 'simplebar-core' edition?

No, actually this is the reason 'simplebar-core' was created in the first place, to get rid of this.
This way of initializing Simplebar is only useful for vanilla JS. The whole point of having specific versions of Simplebar for frameworks like Angular is to provide better integration and so not need any `new SimpleBar(...)` but instead being used as a regular component of the echosystem of the framework.

> Is it true that whole edition 'simplebar' uses .queryAll("[data-simplebar]) to support the directive way of initialization and that this way may cause performance issues?

It doesn't necessarily cause performance issues but if you use this for an Angular application that may eventually not work properly for example if your view changes, like during navigation. Because the simplebar element might be removed and added again, which would not instantiate simplebar properly the second time.

Hope this makes sense!

Also for anyone reading this, I didn't officially release the `simplebar-core` (it's in beta tag atm) as I didn't get the time (and the need) to finish it.
