### ISSUE TITLE
Nested simplebars

### ISSUE THREAD

**Issue by ParadiseCircus** [Grsmto/simplebar#88]
Is the plugin capable of handling nested scrollbars?

This is the problem I'm running into... when I remove simplebar from the parent it behaves properly, but when nested it adds a padding and the vertical trail takes spaces where the simplebar child is located.

![playlist](https://cloud.githubusercontent.com/assets/5393485/26650045/cd39526a-460d-11e7-98df-1397b4672d88.png)

**Comment by holaneph** [comment]
I have that same issue.

**Comment by ParadiseCircus** [comment]
Here's a plunker replicating the issue.

https://plnkr.co/edit/iOk6YKtawyFwrH1ieLRl?p=preview

**Comment by Grsmto** [comment]
Thanks for this, I'll take a look!

**Comment by luchomatic** [comment]
I had this issue and fixed it by using data-simplebar on the inner elements, but for the big container I initialized it with javascript after the inner elements where initialized.

I also had to add overflow-x: hidden !important; on the inner elements so that the first element wouldn't show a tiny bar that would controll the container element.

**Comment by cooltolia** [comment]
After migrating from version 4 to 5 I've experienced the same problem. 

I have a filter with initialized scrollbar.  And there is several sections (firstly hidden by display:none).
When using version 4, scrollbar of this sections was always in place after visibility change. But not with 5 version.
luchomatic hack helped me, but I wonder, @Grsmto, may be there is a better approach? And what is the reason of this behavior

[https://codepen.io/cooltolia/pen/pojNEmL] -- made an example. Change lib version to 5 to see bug
