### ISSUE TITLE
Parent element padding not included

### ISSUE THREAD

**Issue by thexeos** [Grsmto/simplebar#90]
When the target element (`[data-simplebar="init"]`) has right padding (6px in this case), the `.simplebar-scroll-content` should also have the same padding added to the "scrollbar width" padding. Otherwise the native scrollbar becomes visible.

*[data-simplebar="init"]* (6px right-padding)
![image](https://user-images.githubusercontent.com/2260539/27455187-5afde3b2-5794-11e7-99d4-7f82e9b94ed7.png)

*.simplebar-scroll-content* (20px right-padding and 26px right-padding)
![image](https://user-images.githubusercontent.com/2260539/27455424-1c15932e-5795-11e7-9e7c-62ea21f0d1cf.png) ![image](https://user-images.githubusercontent.com/2260539/27455427-1ec47a18-5795-11e7-8ad3-692f7ad60e04.png)

**Comment by Grsmto** [comment]
You would have to add the padding by another way (like adding a container div).

I think we can't really handle every possible CSS scenarios and if I start to implement hacks to clone CSS applied to the parent element, there will be plenty of other CSS attributes that can break the plugin.
Of course I'm open to solutions if someone think that there is actually not many CSS props.
If you want a plugin that doesn't manipulate the DOM (and so this kind of issue won't happen) you should maybe try https://github.com/noraesae/perfect-scrollbar

**Comment by thexeos** [comment]
The only way to add the missing padding is to change the inline style generated by the plugin.

Here is the JSFiddle that reproduces it: [JSFiddle](https://jsfiddle.net/57obe5w2/) The padding is applied to the element, which is passed to the constructor. The only attribute that causes the native scrollbar to show is padding. Other two "spacing" attributes (border and margin) are added outside of the scrollable area.

**Comment by trefrog** [comment]
my specific scenario, for example, and what I did to fix it... I've tried to make it as generic as possible. maybe my implementation of bootstrap is flawed... but I stripped everything down to just the necessary parts

https://www.codeply.com/go/2l4FgJ1744

**Comment by Grsmto** [comment]
Hi guys,

I'm not 100% sure that's the problem you encountered but the solution for this can be seen on this jsfiddle, you can see I applied a `padding-right: 60px` on the container: https://jsfiddle.net/Grsmto/y6fj691y/7/

The div on which you apply SimpleBar should be empty of any "layout"  css property, otherwise it can break SimpleBar calculations. So if you want to add like, a padding, you'll have to add an extra container div where you apply your padding.

I don't want to start trying to "read" the css of the user and try to patch SimpleBar based on that cause it seems like a slippery slope to me (too many scenarios to handle) so I prefer to let that to the user!

Hope this help!

**Comment by michaelkolber** [comment]
Can this perhaps be added to the Caveats section in the README? I had to search to find this, and while the solution was as easy as adding a container, having it on the repo's homepage would have been helpful.
